### ISSUE TITLE
Perform some computations using Apache Spark (Greek Letters)

### ISSUE THREAD

**Issue by angelip2303** [xondemingo/stock-prices-empathy-academy#7]
## User Story:

AS A data engineer,
I WANT TO utilize Apache Spark to perform computations on the stock prices data,
SO THAT I can analyze and derive insights from the data for further analysis and decision-making.

## Acceptance Criteria:

- [X] The data should be processed and transformed using Apache Spark's built-in functions and libraries, such as DataFrame or RDD operations, to perform computations on the data, such as filtering, windows and transformations, as required for the analysis.
- [X] The computations should be performed efficiently and at scale, leveraging Apache Spark's distributed computing capabilities to process large volumes of data in a timely manner, and utilizing Spark's optimizations for performance and scalability.
- [x] Optional: Use Linear Regression to calculate beta coefficient of the stocks to know its volatibility with respect to the market

As a result, the data engineer will be able to utilize Apache Spark to perform computations on the stock prices dataset, enabling analysis and insights for further analysis and decision-making.

**Comment by manmanrod** [comment]
Beta is calculated using pandas pct_change function and a Linear Regression model. I have left a comment on how pct_change could be replaced with an implementation using pySpark's windows. The problem here is that Spark's context cannot be used inside a UDF (User Defined Function).

No more "greek letters" could be calculated due to its complexity and lack of knowledge in advanced finance.
